### ISSUE TITLE
Timestamp is a String in CustomPatternLayout

### ISSUE THREAD

**Issue by jaypatel512** [log4mongo/log4mongo-java#13]
When we use a default LoggingAppender, the timestamp field is actually a mongo date object, while in custom pattern layout, it is stored as a string object. We need to stick to either one of the standard.

**Comment by pramodransingh** [comment]
Created pull request to resolve above issue.

**Comment by RobertStewart** [comment]
This was implemented by @pramodransingh in https://github.com/log4mongo/log4mongo-java/pull/40
