### ISSUE TITLE
Switch from the deprecated Mongo class to MongoClient

### ISSUE THREAD

**Issue by RobertStewart** [log4mongo/log4mongo-java#27]
The [Mongo](http://api.mongodb.org/java/current/com/mongodb/Mongo.html) class that defaults to unsafe writes has been deprecated in recent versions of the Java driver. Log4mongo should be using the [MongoClient](http://api.mongodb.org/java/current/com/mongodb/MongoClient.html) class.

**Comment by scheras** [comment]
See #31 .

**Comment by RobertStewart** [comment]
Thanks to an awesome contribution by @scheras, this is resolved.
